/**
 * 同步品牌数据
 * 读取飞书电子表格 → 生成 src/data/brands.ts
 */

import { getSheetValues } from './client';
import * as fs from 'fs';
import * as path from 'path';

interface Brand {
  id: string;
  slug: string;
  name: Record<string, string>;
  tagline: Record<string, string>;
  description: Record<string, string>;
  primaryColor: string;
  website?: string;
}

function getCell(row: (string | number | boolean | object)[], idx: number): string {
  const v = row[idx];
  if (v === undefined || v === null) return '';
  // 飞书 URL 类型：{link, text, type} 或直接是字符串
  if (typeof v === 'object' && !Array.isArray(v)) {
    return (v as { link?: string; text?: string }).link || (v as { text?: string }).text || '';
  }
  if (Array.isArray(v)) {
    const item = v[0];
    if (typeof item === 'object') return (item as { link?: string; text?: string }).link || '';
    return String(item);
  }
  return String(v);
}

async function syncBrands(): Promise<Brand[]> {
  const sheetToken = process.env.FEISHU_SHEET_BRANDS_TOKEN;
  const sheetId = process.env.FEISHU_SHEET_BRANDS_ID;
  if (!sheetToken || !sheetId) {
    throw new Error('Missing env: FEISHU_SHEET_BRANDS_TOKEN and FEISHU_SHEET_BRANDS_ID');
  }

  const rows = await getSheetValues(sheetToken, sheetId, 'A1:G50');
  const dataRows = rows.slice(1); // 跳过表头

  const brands: Brand[] = [];
  for (const row of dataRows) {
    if (row.length === 0 || getCell(row, 0) === '') continue;

    const website = getCell(row, 6);
    brands.push({
      id: getCell(row, 0),
      slug: getCell(row, 1),
      name: { en: getCell(row, 2) },
      tagline: { en: getCell(row, 3) },
      description: { en: getCell(row, 4) },
      primaryColor: getCell(row, 5) || '#2563EB',
      website: website || undefined,
    });
  }

  return brands;
}

function generateBrandsFile(brands: Brand[]): string {
  const lines: string[] = [];
  lines.push(`// Generated by scripts/feishu/sync.ts — do not edit manually`);
  lines.push(`// Sync: npx tsx scripts/feishu/sync.ts brands`);
  lines.push(``);
  lines.push(`export interface Brand {`);
  lines.push(`  id: string;`);
  lines.push(`  slug: string;`);
  lines.push(`  name: Record<string, string>;`);
  lines.push(`  tagline: Record<string, string>;`);
  lines.push(`  description: Record<string, string>;`);
  lines.push(`  logo?: string;`);
  lines.push(`  primaryColor: string;`);
  lines.push(`  website?: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const brands: Brand[] = [`);

  for (const b of brands) {
    lines.push(`  {`);
    lines.push(`    id: '${b.id}',`);
    lines.push(`    slug: '${b.slug}',`);
    lines.push(`    name: { en: '${b.name.en}' },`);
    lines.push(`    tagline: { en: '${b.tagline.en}' },`);
    lines.push(`    description: { en: '${b.description.en}' },`);
    lines.push(`    primaryColor: '${b.primaryColor}',`);
    lines.push(`    website: ${b.website ? `'${b.website}'` : 'undefined'},`);
    lines.push(`  },`);
  }

  lines.push(`];`);
  lines.push(``);
  lines.push(`export function getBrand(idOrSlug: string): Brand | undefined {`);
  lines.push(`  return brands.find(b => b.id === idOrSlug || b.slug === idOrSlug);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getBrandBySlug(slug: string): Brand | undefined {`);
  lines.push(`  return brands.find(b => b.slug === slug);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getAllBrands(): Brand[] {`);
  lines.push(`  return brands;`);
  lines.push(`}`);

  return lines.join('\n');
}

export async function run() {
  console.log('🏷️  Syncing brands from Feishu...');

  try {
    const brands = await syncBrands();
    console.log(`   Found ${brands.length} brands`);

    const output = generateBrandsFile(brands);
    const outputPath = path.resolve(process.cwd(), 'src/data/brands.ts');
    fs.writeFileSync(outputPath, output, 'utf-8');

    console.log(`   ✅ Written to src/data/brands.ts`);
    return { brands, count: brands.length };
  } catch (err) {
    console.error(`   ❌ Failed to sync brands: ${err}`);
    process.exit(1);
  }
}
