/**
 * 同步竞品对照数据
 * 读取飞书电子表格 → 生成 src/data/crossReference.ts
 */

import { getSheetValues } from './client';
import * as fs from 'fs';
import * as path from 'path';

interface CrossRefItem {
  tongjing: string;
  epson?: string;
  ndk?: string;
  kds?: string;
  murata?: string;
  package: '3225' | '2520' | '2016' | '1610';
  productId: string;
}

function getCell(row: (string | number | boolean)[], idx: number): string {
  const v = row[idx];
  return v !== undefined && v !== null ? String(v) : '';
}

async function syncCrossRef(): Promise<CrossRefItem[]> {
  const sheetToken = process.env.FEISHU_SHEET_CROSSREF_TOKEN;
  const sheetId = process.env.FEISHU_SHEET_CROSSREF_ID;
  if (!sheetToken || !sheetId) {
    throw new Error('Missing env: FEISHU_SHEET_CROSSREF_TOKEN and FEISHU_SHEET_CROSSREF_ID');
  }

  const rows = await getSheetValues(sheetToken, sheetId, 'A1:G50');
  const dataRows = rows.slice(1);

  const items: CrossRefItem[] = [];
  for (const row of dataRows) {
    if (row.length === 0 || getCell(row, 0) === '') continue;

    const epson = getCell(row, 1);
    const ndk = getCell(row, 2);
    const kds = getCell(row, 3);
    const murata = getCell(row, 4);

    items.push({
      tongjing: getCell(row, 0),
      epson: epson || undefined,
      ndk: ndk || undefined,
      kds: kds || undefined,
      murata: murata || undefined,
      package: getCell(row, 5) as CrossRefItem['package'],
      productId: getCell(row, 6),
    });
  }

  return items;
}

function generateCrossRefFile(items: CrossRefItem[]): string {
  const lines: string[] = [];
  lines.push(`// Generated by scripts/feishu/sync.ts — do not edit manually`);
  lines.push(`// Sync: npx tsx scripts/feishu/sync.ts crossref`);
  lines.push(``);
  lines.push(`export interface CrossRefItem {`);
  lines.push(`  tongjing: string;`);
  lines.push(`  epson?: string;`);
  lines.push(`  ndk?: string;`);
  lines.push(`  kds?: string;`);
  lines.push(`  murata?: string;`);
  lines.push(`  package: '3225' | '2520' | '2016' | '1610';`);
  lines.push(`  productId: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export interface CrossRefProduct extends CrossRefItem {`);
  lines.push(`  href: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const crossRefData: CrossRefItem[] = [`);

  for (const c of items) {
    const parts: string[] = [];
    parts.push(`tongjing: '${c.tongjing}'`);
    if (c.epson) parts.push(`epson: '${c.epson}'`);
    if (c.ndk) parts.push(`ndk: '${c.ndk}'`);
    if (c.kds) parts.push(`kds: '${c.kds}'`);
    if (c.murata) parts.push(`murata: '${c.murata}'`);
    parts.push(`package: '${c.package}' as const`);
    parts.push(`productId: '${c.productId}'`);
    lines.push(`  { ${parts.join(', ')} },`);
  }

  lines.push(`];`);
  lines.push(``);
  lines.push(`export function getCrossRefWithHref(): CrossRefProduct[] {`);
  lines.push(`  return crossRefData.map(item => ({`);
  lines.push(`    ...item,`);
  lines.push(`    href: \`/products/\${item.productId}\`,`);
  lines.push(`  }));`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function searchCrossRef(query: string, brand?: string): CrossRefProduct[] {`);
  lines.push(`  if (!query && !brand) return getCrossRefWithHref();`);
  lines.push(`  if (!query) return getCrossRefWithHref().filter(item => {`);
  lines.push(`    const brandKey = brand as keyof CrossRefItem;`);
  lines.push(`    return item[brandKey] !== undefined;`);
  lines.push(`  });`);
  lines.push(``);
  lines.push(`  const q = query.toLowerCase().trim();`);
  lines.push(`  return getCrossRefWithHref().filter(item => {`);
  lines.push(`    if (brand && brand !== 'all') {`);
  lines.push(`      const brandKey = brand as keyof CrossRefItem;`);
  lines.push(`      const brandValue = item[brandKey];`);
  lines.push(`      if (brandValue && !brandValue.toLowerCase().includes(q)) return false;`);
  lines.push(`    } else {`);
  lines.push(`      const searchStr = \`\${item.tongjing} \${item.epson || ''} \${item.ndk || ''} \${item.kds || ''} \${item.murata || ''}\`.toLowerCase();`);
  lines.push(`      if (!searchStr.includes(q)) return false;`);
  lines.push(`    }`);
  lines.push(`    return true;`);
  lines.push(`  });`);
  lines.push(`}`);

  return lines.join('\n');
}

export async function run() {
  console.log('🔗 Syncing cross-reference from Feishu...');

  try {
    const items = await syncCrossRef();
    console.log(`   Found ${items.length} cross-reference entries`);

    const output = generateCrossRefFile(items);
    const outputPath = path.resolve(process.cwd(), 'src/data/crossReference.ts');
    fs.writeFileSync(outputPath, output, 'utf-8');

    console.log(`   ✅ Written to src/data/crossReference.ts`);
    return { items, count: items.length };
  } catch (err) {
    console.error(`   ❌ Failed to sync cross-reference: ${err}`);
    process.exit(1);
  }
}
