/**
 * 同步产品数据
 * 读取飞书电子表格 → 生成 src/data/products.ts
 */

import { getSheetValues } from './client';
import * as fs from 'fs';
import * as path from 'path';

// 飞书电子表格配置（通过环境变量设置）
// FEISHU_SHEET_PRODUCTS_TOKEN=电子表格token
// FEISHU_SHEET_PRODUCTS_ID=sheetId（可在飞书表格URL中找到）

// 列索引（0-based，从 A=0 开始）
// A=0 id, B=1 brandId, C=2 model, D=3 category, E=4 frequency,
// F=5 tolerance, G=6 package, H=7 loadCapacitance, I=8 esr,
// J=9 stock, K=10 priceRange, L=11 badge,
// M=12 pkg_width, N=13 pkg_height, O=14 pkg_depth,
// P=15 load_cap, Q=16 esr_max, R=17 op_temp

interface Product {
  id: string;
  brandId: string;
  model: string;
  category: 'resonator' | 'oscillator' | 'rtc';
  frequency: string;
  tolerance: string;
  package: string;
  loadCapacitance: string;
  esr: string;
  stock: string;
  priceRange: string;
  badge: 'hot' | 'new' | 'default' | 'discontinued' | 'futures';
  specifications: Record<string, string>;
}

function colVal(row: (string | number | boolean)[], idx: number): string {
  const v = row[idx];
  return v !== undefined && v !== null ? String(v) : '';
}

async function syncProducts(): Promise<Product[]> {
  const sheetToken = process.env.FEISHU_SHEET_PRODUCTS_TOKEN;
  const sheetId = process.env.FEISHU_SHEET_PRODUCTS_ID;
  if (!sheetToken || !sheetId) {
    throw new Error('Missing env: FEISHU_SHEET_PRODUCTS_TOKEN and FEISHU_SHEET_PRODUCTS_ID');
  }
  // 读取表头 + 数据（假设最多 100 行）
  const rows = await getSheetValues(sheetToken, sheetId, 'A1:R100');
  const dataRows = rows.slice(1); // 跳过表头

  const products: Product[] = [];

  for (const row of dataRows) {
    if (row.length === 0 || colVal(row, 0) === '') continue;

    const pkgW = colVal(row, 12);
    const pkgH = colVal(row, 13);
    const pkgD = colVal(row, 14);

    products.push({
      id: colVal(row, 0),
      brandId: colVal(row, 1),
      model: colVal(row, 2),
      category: colVal(row, 3) as Product['category'],
      frequency: colVal(row, 4),
      tolerance: colVal(row, 5),
      package: colVal(row, 6),
      loadCapacitance: colVal(row, 7),
      esr: colVal(row, 8),
      stock: colVal(row, 9),
      priceRange: colVal(row, 10),
      badge: colVal(row, 11) as Product['badge'],
      specifications: {
        Package: pkgW && pkgH && pkgD ? `${pkgW}×${pkgH}×${pkgD}mm` : 'N/A',
        'Load Capacitance': colVal(row, 15) || 'N/A',
        ESR: colVal(row, 16) || 'N/A',
        'Operating Temp': colVal(row, 17) || '-40°C to +85°C',
      },
    });
  }

  return products;
}

function generateProductsFile(products: Product[]): string {
  const lines: string[] = [];
  lines.push(`// Generated by scripts/feishu/sync.ts — do not edit manually`);
  lines.push(`// Sync: npx tsx scripts/feishu/sync.ts products`);
  lines.push(``);
  lines.push(`export interface Product {`);
  lines.push(`  id: string;`);
  lines.push(`  brandId: string;`);
  lines.push(`  model: string;`);
  lines.push(`  category: 'resonator' | 'oscillator' | 'rtc';`);
  lines.push(`  frequency: string;`);
  lines.push(`  tolerance: string;`);
  lines.push(`  package: string;`);
  lines.push(`  loadCapacitance: string;`);
  lines.push(`  esr: string;`);
  lines.push(`  stock: string;`);
  lines.push(`  priceRange: string;`);
  lines.push(`  badge: 'hot' | 'new' | 'default' | 'discontinued' | 'futures';`);
  lines.push(`  specifications: Record<string, string>;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const products: Product[] = [`);

  for (const p of products) {
    const specs = Object.entries(p.specifications)
      .map(([k, v]) => `      '${k}': '${v}'`)
      .join(',\n');
    lines.push(`  {`);
    lines.push(`    id: '${p.id}',`);
    lines.push(`    brandId: '${p.brandId}',`);
    lines.push(`    model: '${p.model}',`);
    lines.push(`    category: '${p.category}',`);
    lines.push(`    frequency: '${p.frequency}',`);
    lines.push(`    tolerance: '${p.tolerance}',`);
    lines.push(`    package: '${p.package}',`);
    lines.push(`    loadCapacitance: '${p.loadCapacitance}',`);
    lines.push(`    esr: '${p.esr}',`);
    lines.push(`    stock: '${p.stock}',`);
    lines.push(`    priceRange: '${p.priceRange}',`);
    lines.push(`    badge: '${p.badge}',`);
    lines.push(`    specifications: {`);
    lines.push(specs);
    lines.push(`    },`);
    lines.push(`  },`);
  }

  lines.push(`];`);
  lines.push(``);
  lines.push(`export function getProductsByBrand(brandId: string): Product[] {`);
  lines.push(`  return products.filter(p => p.brandId === brandId);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getProductBySlug(id: string): Product | undefined {`);
  lines.push(`  return products.find(p => p.id === id);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getProductByModel(model: string): Product | undefined {`);
  lines.push(`  return products.find(p => p.model === model);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getAllProducts(): Product[] {`);
  lines.push(`  return products;`);
  lines.push(`}`);

  return lines.join('\n');
}

export async function run() {
  console.log('📦 Syncing products from Feishu...');

  try {
    const products = await syncProducts();
    console.log(`   Found ${products.length} products`);

    const output = generateProductsFile(products);
    const outputPath = path.resolve(process.cwd(), 'src/data/products.ts');
    fs.writeFileSync(outputPath, output, 'utf-8');

    console.log(`   ✅ Written to src/data/products.ts`);
    return { products, count: products.length };
  } catch (err) {
    console.error(`   ❌ Failed to sync products: ${err}`);
    process.exit(1);
  }
}
