// Article data loaded from articles.json (generated by prebuild from Feishu)
import articlesData from './articles.json';

export interface Article {
  slug: string;
  title: string;
  category: 'tech' | 'industry' | 'company';
  date: string;
  author: string;
  excerpt: string;
  content: string;
  image?: string;
  url?: string;  // Feishu document URL
}

// Transform raw article data to Article interface
function transformArticle(raw: any): Article {
  // Generate slug from id or title
  const slug = raw.slug || raw.id || raw.title?.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') || 'article';

  // Determine category from title or default to tech
  let category: Article['category'] = 'tech';
  const titleLower = (raw.title || '').toLowerCase();
  if (titleLower.includes('industry') || titleLower.includes('趋势') || titleLower.includes('市场')) {
    category = 'industry';
  } else if (titleLower.includes('company') || titleLower.includes('公司') || titleLower.includes('认证') || titleLower.includes('achievement')) {
    category = 'company';
  }

  return {
    slug,
    title: raw.title || 'Untitled',
    category,
    date: raw.lastSync ? new Date(raw.lastSync).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
    author: raw.author || 'China NewChip',
    excerpt: raw.excerpt || raw.title || '',
    content: raw.content || `## ${raw.title || 'Article Content'}\n\nThis article is synced from Feishu. Full content will be available once the Feishu sync is properly configured.`,
    image: raw.image || undefined,
    url: raw.url || raw.docUrl || undefined,
  };
}

// Load articles from JSON
const rawArticles: any[] = Array.isArray(articlesData) ? articlesData : [];
export const articles: Article[] = rawArticles.map(transformArticle);

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}

export function getAllArticles(): Article[] {
  return articles;
}

export function getArticlesByCategory(category: Article['category']): Article[] {
  return articles.filter((a) => a.category === category);
}
