// Generated by scripts/feishu/sync.ts — do not edit manually
// Sync: npx tsx scripts/feishu/sync.ts articles
// Note: New articles added manually until Feishu docx write API is stable.

export interface Article {
  slug: string;
  title: string;
  category: 'tech' | 'industry' | 'company';
  date: string;
  author: string;
  excerpt: string;
  content: string;
  image?: string;
}

export const articles: Article[] = [
  {
    slug: 'working-principle-and-applications-of-crystal-resonators',
    title: "Working Principle and Applications of Crystal Resonators",
    category: 'tech' as const,
    date: '2026-04-21',
    author: "China NewChip",
    excerpt: "Crystal resonators are fundamental components in modern electronics, providing highly stable frequency references for everything from smartphones to industrial control systems. Their reliability and precision make them indispensable in applications where timing accuracy is critical.",
    content: `
## Introduction
Crystal resonators are fundamental components in modern electronics, providing highly stable frequency references for everything from smartphones to industrial control systems. Their reliability and precision make them indispensable in applications where timing accuracy is critical.
## How Crystal Resonators Work
Crystal resonators utilize the piezoelectric effect of quartz crystal. When an electric field is applied to a quartz crystal, it mechanically deforms. Conversely, when mechanical stress is applied, it generates an electrical charge. This bidirectional conversion allows the crystal to vibrate at precise frequencies.
The resonant frequency is determined by:
- Crystal cut — The angle at which the crystal is cut from the raw quartz
- Crystal dimensions — Thickness and shape of the quartz blank
- Operating temperature — Frequency stability varies with temperature
## Key Specifications
### Frequency Tolerance
Measured in parts per million (ppm), this indicates how much the actual frequency may deviate from the nominal value at 25°C. Common tolerances range from ±10ppm to ±50ppm.
### Load Capacitance
The external capacitance required to achieve the rated frequency. Typical values include 8pF, 12pF, and 20pF. Matching the load capacitance to your circuit is crucial for accurate frequency operation.
### Equivalent Series Resistance (ESR)
Lower ESR means less power loss and better performance. Modern crystal resonators typically have ESR values between 30Ω and 100Ω depending on the package size and frequency.
## Applications
### Consumer Electronics
- Smartphones and tablets
- Wearable devices
- Gaming consoles
- Audio equipment
### Industrial Systems
- PLC controllers
- Motor control systems
- Power electronics
- Industrial automation
### Automotive Electronics
- Engine control units (ECU)
- In-vehicle networking
- Safety systems
- Infotainment
## Selection Guide
When choosing a crystal resonator, consider:
1. Required frequency and tolerance
1. Package size constraints
1. Operating temperature range
1. Load capacitance requirements
1. ESR limitations for your circuit
Our product line offers crystal resonators in packages from 1610 to 3225, with frequencies ranging from 8MHz to 50MHz, meeting AEC-Q100 automotive standards.
`,
  },
  {
    slug: '2026-crystal-oscillator-industry-development-trend-analysis',
    title: "2026 Crystal Oscillator Industry Development Trend Analysis",
    category: 'industry' as const,
    date: '2026-04-21',
    author: "China NewChip",
    excerpt: "The global crystal resonator market is experiencing unprecedented growth, driven by several converging trends in telecommunications, automotive, and consumer electronics sectors.",
    content: `
## Market Overview
The global crystal resonator market is experiencing unprecedented growth, driven by several converging trends in telecommunications, automotive, and consumer electronics sectors.
## Key Trends for 2026
### 1. 5G Infrastructure Expansion
The continued rollout of 5G networks worldwide is creating massive demand for high-precision timing components. Base stations require crystals with excellent frequency stability and temperature characteristics.
### 2. Automotive Electronics Growth
The transition to electric vehicles and autonomous driving is accelerating demand for automotive-grade crystal resonators. Requirements include:
- AEC-Q100/Q200 certification
- Extended temperature range (-40°C to +125°C)
- High reliability and long lifecycle
### 3. IoT Proliferation
Billions of connected devices require affordable, reliable timing solutions. The trend toward smaller packages (1610, 2016) continues as devices become more compact.
### 4. Miniaturization
Product designers increasingly demand smaller crystal packages without sacrificing performance. This has driven innovation in wafer-level packaging, improved crystal cutting techniques, and enhanced temperature compensation.
## Technology Advancements
### Improved Temperature Stability
New crystal cuts and compensation techniques are enabling tighter frequency tolerance over wider temperature ranges.
### Lower ESR
Advanced manufacturing processes are producing crystals with consistently low equivalent series resistance.
### Higher Frequency Ranges
Traditionally, MHz-range crystals dominated. Now, demand is growing for higher frequencies in smaller packages.
## Regional Insights
### China
Chinese manufacturers are rapidly advancing in technology and quality, now competing with traditional Japanese brands in the global market.
### Japan
Japanese manufacturers maintain strong positions in high-precision and automotive segments.
### Southeast Asia
Emerging as a hub for consumer electronics manufacturing, driving local demand.
## Conclusion
The crystal resonator industry is adapting to meet the demands of next-generation electronics. Quality, reliability, and miniaturization remain the key focus areas for manufacturers worldwide.
`,
  },
  {
    slug: 'tongjing-electronics-achieves-aec-q100-certification',
    title: "TongJing Electronics Achieves AEC-Q100 Certification",
    category: 'company' as const,
    date: '2026-04-21',
    author: "China NewChip",
    excerpt: "We are proud to announce that TongJing Electronics' RTC module product line has successfully achieved AEC-Q100 certification, a critical milestone for automotive electronics components.",
    content: `
## Certification Achievement
We are proud to announce that TongJing Electronics' RTC module product line has successfully achieved AEC-Q100 certification, a critical milestone for automotive electronics components.
## What is AEC-Q100?
AEC-Q100 is the automotive-grade stress test qualification for integrated circuits. For crystal resonators and oscillators, it ensures:
- Temperature Range: Operation from -40°C to +125°C
- Reliability: Passed rigorous life-cycle testing
- Quality: Manufactured under strict quality control systems
- Documentation: Complete traceability and failure analysis capability
## Certification Process
The certification process involved:
1. Design Verification: Rigorous analysis of design margins and reliability
1. Wafer-level Testing: Comprehensive electrical characterization
1. Packaging Stress Tests: Mechanical and thermal stress testing
1. Reliability Monitoring: Extended life testing under various conditions
1. Audit: Quality system audit by independent laboratory
## Quality Commitment
This certification reinforces our commitment to providing automotive-grade electronic components that meet the highest standards of reliability and performance.
`,
  },
  {
    slug: 'how-to-choose-the-right-crystal-resonator-package',
    title: "How to Choose the Right Crystal Resonator Package",
    category: 'tech' as const,
    date: '2026-04-21',
    author: "China NewChip",
    excerpt: "Crystal resonators come in standardized surface-mount packages. The package size indicates the dimensions in millimeters.",
    content: `
## Understanding Package Sizes
Crystal resonators come in standardized surface-mount packages. The package size indicates the dimensions in millimeters:
- 3225: 3.2 × 2.5 × 0.8mm
- 2520: 2.5 × 2.0 × 0.65mm
- 2016: 2.0 × 1.6 × 0.5mm
- 1610: 1.6 × 1.0 × 0.35mm
## Selection Criteria
### 1. Board Space Constraints
Modern electronics demand increasingly compact designs. Consider: Smartphones and Wearables prefer 1610/2016 packages. Tablets prefer 2016/2520. Industrial and Automotive applications typically use 2520/3225.
### 2. Frequency Requirements
Different packages support different frequency ranges. 1610 suits 24MHz to 50MHz best. 2016 covers 16MHz to 50MHz. 2520 handles 12MHz to 50MHz. 3225 is most versatile at 8MHz to 50MHz.
### 3. ESR Considerations
Smaller packages typically have higher ESR. At 26MHz: 3225 = 30Ω, 2520 = 40Ω, 2016 = 50Ω, 1610 = 60Ω.
### 4. Temperature Range
Automotive and industrial applications may require extended temperature range. Consumer grade: -20°C to +70°C. Industrial: -40°C to +85°C. Automotive: -40°C to +125°C.
## Practical Recommendations
### High-Precision Applications
Choose 3225 or 2520 packages with tight tolerance (±10ppm) for best performance.
### Space-Constrained Designs
Opt for 2016 or 1610 packages in compact devices. Modern manufacturing ensures reliable solderability despite smaller size.
### High-Frequency Applications
For frequencies above 40MHz, 3225 packages offer the best ESR performance.
### Cost-Sensitive Projects
Larger packages (3225) are typically more economical due to established manufacturing processes.
## Conclusion
Package selection is a balance between size constraints, performance requirements, and cost considerations. When in doubt, consult with our technical team for recommendations specific to your application.
`,
  },
  {
    slug: 'understanding-frequency-tolerance-and-stability',
    title: "Understanding Frequency Tolerance and Stability in Crystal Resonators",
    category: 'tech' as const,
    date: '2026-04-15',
    author: "China NewChip",
    excerpt: "Frequency tolerance and stability are the two most critical specifications when selecting a crystal resonator. This article explains the difference, measurement methods, and how temperature affects crystal performance.",
    content: `
## What Is Frequency Tolerance?
Frequency tolerance measures how much the actual resonant frequency may deviate from the nominal value at 25°C. It is expressed in parts per million (ppm). A ±10ppm crystal rated at 16MHz may oscillate anywhere between 16.00016MHz and 15.99984MHz at room temperature.
Common tolerance grades:
- ±10ppm — Precision applications
- ±20ppm — Standard general purpose
- ±30ppm — Consumer electronics
- ±50ppm — Cost-sensitive applications
The tighter the tolerance, the more expensive the crystal typically becomes.
## What Is Frequency Stability?
Frequency stability measures how much the frequency drifts across temperature ranges. Unlike tolerance (a one-time offset at 25°C), stability describes the drift curve from -40°C to +85°C or -40°C to +125°C for automotive grades.
Stability is typically expressed in ppm over the operating temperature range. A crystal with ±30ppm stability over -40°C to +85°C means the frequency stays within ±30ppm of nominal across the entire temperature range.
## Temperature Compensation Methods
### AT-Cut Crystals
The most common cut, with a zero temperature coefficient around 25°C. Provides good stability from -40°C to +85°C.
### Stress-Compensated (SC) Cuts
Used in high-stability oscillators, better at resisting mechanical stress effects.
### Temperature-Compensated Crystal Oscillators (TCXO)
Use a compensation circuit to actively correct frequency drift. Typical stability: ±0.5ppm to ±2.5ppm.
### Oven-Controlled Crystal Oscillators (OCXO)
Maintain crystal at constant temperature. Best stability: ±0.001ppm to ±0.1ppm. Used in base stations and precision timing.
## How to Select the Right Tolerance and Stability
### Consumer Electronics
Smartwatches, IoT sensors: ±20ppm to ±30ppm is sufficient. Cost and power consumption are primary concerns.
### Industrial Control
PLC, motor drives: ±10ppm to ±20ppm. Reliability across wide temperature ranges matters.
### Automotive
ECU, ADAS: AEC-Q200 compliant, ±10ppm to ±20ppm over -40°C to +125°C. Vibration resistance also critical.
### Telecom Infrastructure
Base stations, sync equipment: ±0.01ppm to ±0.5ppm. OCXO or high-end TCXO required.
`,
  },
  {
    slug: 'smd-crystal-packages-size-guide',
    title: "SMD Crystal Packages: From 1610 to 7050 — A Complete Size Guide",
    category: 'tech' as const,
    date: '2026-04-10',
    author: "China NewChip",
    excerpt: "Surface-mount crystal packages have standardized around a handful of common sizes. Understanding the dimensions, thermal characteristics, and mechanical suitability of each package helps you select the right crystal for your application.",
    content: `
## Standard SMD Package Sizes
Crystal packages are named after their approximate dimensions in hundredths of a millimeter. A 3225 crystal measures 3.2mm × 2.5mm × 0.75mm (typical height varies by manufacturer).
## 1610 Package (1.6mm × 1.0mm)
Dimensions: 1.6mm × 1.0mm × 0.3mm. The smallest standard SMD crystal package available. Primarily used in wearables and space-constrained IoT devices.
Typical frequencies: 26MHz to 52MHz. ESR typically 60Ω to 100Ω due to small crystal blank. Load capacitance 8pF standard.
Limitations: Difficult to solder in manual rework due to small pads. Higher sensitivity to board flex stress.
## 2016 Package (2.0mm × 1.6mm)
Dimensions: 2.0mm × 1.6mm × 0.45mm. A popular choice for smartphones and tablets. Good balance between size and performance.
Typical frequencies: 16MHz to 52MHz. ESR typically 40Ω to 60Ω. Load capacitance 8pF or 12pF.
Height allows for better crystal blank thickness, improving frequency stability compared to 1610.
## 2520 Package (2.0mm × 2.5mm)
Dimensions: 2.5mm × 2.0mm × 0.55mm. Widely used in industrial and automotive applications. Excellent balance of solderability and performance.
Typical frequencies: 8MHz to 54MHz. ESR typically 30Ω to 50Ω. Good thermal dissipation and mechanical robustness.
AEC-Q100/200 compliant versions available. Preferred package for automotive electronics.
## 3225 Package (3.2mm × 2.5mm)
Dimensions: 3.2mm × 2.5mm × 0.75mm. The most common SMD crystal package. Used in everything from consumer electronics to industrial controls.
Typical frequencies: 4MHz to 80MHz. ESR typically 20Ω to 40Ω. Available in both ceramic and glass lid packages.
Excellent track record — well-understood mounting and reflow characteristics. Easy to inspect and rework.
## 5032 Package (5.0mm × 3.2mm)
Dimensions: 5.0mm × 3.2mm × 1.0mm. Used for lower frequency crystals (typically 8MHz to 40MHz) and oscillator modules.
Larger size means lower ESR (15Ω to 30Ω) and better frequency stability. Often used as the crystal in TCXO and OCXO modules.
## 7050 Package (7.0mm × 5.0mm)
Dimensions: 7.0mm × 5.0mm × 1.2mm. The largest standard SMD package. Used for low-frequency, high-stability applications.
Typical frequencies: 4MHz to 20MHz. ESR as low as 10Ω. Excellent for reference oscillators and telecom timing circuits.
`,
  },
  {
    slug: 'crystal-resonators-vs-mems-oscillators',
    title: "Crystal Resonators vs. MEMS Oscillators: Making the Right Choice",
    category: 'tech' as const,
    date: '2026-04-05',
    author: "China NewChip",
    excerpt: "Both crystal and MEMS oscillators serve the same fundamental purpose — providing a stable frequency reference. But the underlying physics, performance characteristics, and application fit differ significantly.",
    content: `
## Fundamental Differences
Crystal oscillators use the mechanical resonance of a quartz crystal (piezoelectric effect). MEMS oscillators use a tiny silicon resonator that vibrates at RF frequencies, with the output divided down to the desired frequency.
Crystal: Ageing characteristics are well understood — typically ±1ppm to ±5ppm per year. Long-term stability excellent.
MEMS: Ageing is typically ±3ppm to ±10ppm per year. Silicon resonators age faster than quartz, though the difference narrows in precision compensated designs.
## Frequency Stability Comparison
Standard crystal oscillator: ±20ppm to ±50ppm over -40°C to +85°C. Inexpensive, widely available.
MEMS oscillator (any frequency programmable): ±20ppm to ±50ppm typical. Advantage: any frequency from 1MHz to 220MHz without custom tooling.
TCXO (crystal): ±0.5ppm to ±2.5ppm over -40°C to +85°C. Mature, reliable technology.
MEMS TCXO: ±0.5ppm to ±2.5ppm. Better initial tolerance, slightly worse long-term ageing.
## Startup Time and Power
Crystal oscillators: Startup time typically 2ms to 10ms. Cold start can be longer for large crystals in oscillator circuits.
MEMS oscillators: Startup time typically 1ms to 3ms. The silicon resonator heats up quickly, reaching stable frequency faster.
Power consumption: MEMS oscillators typically consume 1.5mA to 5mA at 3.3V. Crystal oscillators vary widely — TCXOs can consume 10mA to 30mA due to the heating element.
## Vibration and Shock Resistance
Crystal: Sensitive to vibration. High-G mechanical shock can cause frequency jumps or even crystal breakage in severe cases. Can be mitigated with mechanical isolation mounting.
MEMS: Excellent vibration resistance. Silicon resonators are immune to vibration-induced frequency shifts. Ideal for automotive, industrial, and asset tracking applications.
## When to Choose Crystal
High-precision timing applications (telecom base stations, test equipment): OCXOs and high-end TCXOs use crystal for best stability and lowest phase noise.
Lowest BOM cost for standard frequencies (32.768kHz, 8MHz, 16MHz, 26MHz, etc.): Crystal oscillators remain cheaper at scale for standard frequencies.
Long-term reliability where ±5ppm/year ageing is acceptable.
## When to Choose MEMS
High-vibration environments (automotive under-hood, industrial machinery, asset tracking on vehicles).
Applications requiring any frequency from 1MHz to 220MHz: One device can cover all frequencies vs. multiple crystal part numbers.
Rapid development cycles: No crystal matching or tolerance grading required — all frequencies at equal performance.
Programmable output: Some MEMS oscillators allow frequency changes via I2C or SPI after installation.
`,
  },
  {
    slug: 'crystal-selection-guide-esp32-stm32-nrf52',
    title: "Crystal Selection Guide for ESP32, STM32, and Nordic nRF52 MCUs",
    category: 'tech' as const,
    date: '2026-03-28',
    author: "China NewChip",
    excerpt: "Each popular microcontroller platform has specific crystal requirements for its PLL and RF subsystems. Using the wrong crystal can cause UART baud rate errors, WiFi connection failures, or BLE protocol issues.",
    content: `
## ESP32 (Espressif Systems)
The ESP32 requires a 40MHz crystal for its PLL. The on-chip crystal tolerance requirement is ±10ppm for normal operation, but WiFi 802.11b/g/n compliance requires ±10ppm overall system accuracy including crystal tolerance over temperature.
Recommended crystal: 40MHz, ±10ppm over -40°C to +85°C, CL=10pF or 12pF, ESR≤40Ω. SMD3225 package is standard.
The ESP32 has an internal crystal calibration circuit that can compensate for ±10ppm initial tolerance, but it cannot fully compensate for drift across temperature. A tighter tolerance crystal extends the usable temperature range for reliable WiFi.
Second crystal (optional): 32.768kHz for RTC sleep mode timing. Low-ESR (<70kΩ) 12.5pF load recommended.
## STM32 (STMicroelectronics)
STM32 microcontrollers use an external 8MHz crystal (HSE) for the PLL to generate the system clock (up to 480MHz on STM32F4/F7/H7). The PLL multiplies the 8MHz input.
UART baud rate accuracy depends on the HSE crystal tolerance. For UART at 115200 baud with 0% error tolerance on both ends, a ±5ppm crystal is recommended. ±10ppm may cause errors at 230400 baud and above.
For CAN bus applications, the crystal tolerance directly affects bit timing accuracy. CAN 2.0 requires ±0.5% overall accuracy on the bit time. At 500kbps, ±10ppm crystal is sufficient.
Recommended crystal for STM32F4: 8MHz, ±10ppm, CL=8pF to 18pF (check datasheet), ESR≤40Ω. SMD3225 standard.
For USB OTG on STM32F4: USB full-speed requires ±500ppm. An ±10ppm crystal easily meets this.
## Nordic nRF52 Series (nRF52832, nRF52840)
The nRF52 uses a 32MHz crystal for its radio PLL in BLE 5.x operation. The crystal tolerance requirement for BLE is ±40ppm (per the Bluetooth Core Specification), but practical implementations use ±20ppm or ±10ppm for margin.
For nRF52840 with USB: The USB peripheral requires ±500ppm. 32MHz ±10ppm crystal meets this easily.
Recommended crystal for nRF52: 32MHz, ±10ppm, CL=8pF or 10pF, ESR≤40Ω. SMD2520 or SMD3225.
nRF52 also supports an optional 32.768kHz crystal for RTC and low-power timing. Use low-ESR crystal (<70kΩ) for best current consumption during sleep.
## Common Crystal Selection Mistakes
Using a ±30ppm "generic" crystal for ESP32 in outdoor IoT sensor: The temperature drift at 40°C above room temperature pushes total error beyond ±30ppm, causing intermittent WiFi disconnections.
Wrong load capacitance: If the crystal datasheet specifies 12pF load capacitance but the MCU board uses 8pF effective load, the crystal will oscillate at a higher frequency than nominal — causing baud rate and RF issues.
Ignoring ESR: High-ESR crystals (>60Ω for 26MHz to 40MHz) may cause slow startup or failure to oscillate in circuits designed for 30Ω crystals.
`,
  },
  {
    slug: 'global-crystal-oscillator-market-report-2026-2031',
    title: "Global Crystal Oscillator Market Report 2026–2031",
    category: 'industry' as const,
    date: '2026-04-18',
    author: "China NewChip",
    excerpt: "The global crystal oscillator market is projected to grow from $3.2 billion in 2025 to $4.8 billion by 2031, driven by 5G infrastructure expansion, electric vehicle proliferation, and the industrial IoT boom.",
    content: `
## Market Size and Growth Drivers
2025 market size: $3.2 billion USD. CAGR 2026–2031: 7.2%. Key growth regions: Asia-Pacific (60% of global demand), North America (18%), Europe (15%).
5G infrastructure: Each 5G small cell requires 3–5 oscillators (reference clock, PLL, radio). Macro cells require even more. 5G deployment alone will account for 22% of new crystal demand through 2028.
Electric vehicles: A modern EV contains 80–120 crystal oscillators for ECUs, battery management, motor control, V2X, and infotainment. ICE vehicles typically contain 20–40.
Industrial IoT: Edge sensors and controllers in smart factories require crystals for real-time clock, communication timing, and motor control. Each smart factory installation adds 200–500 connected devices, each with 1–3 crystals.
## Technology Shift: From Crystal to MEMS?
MEMS oscillators are gaining share in the ±20ppm to ±50ppm market segment. The ability to program any frequency and faster startup make MEMS attractive for high-mix manufacturing.
However, precision timing (>1ppm stability) remains dominated by TCXO and OCXO crystal-based designs. No MEMS solution currently matches the ±0.001ppm performance of OCXOs for telecom timing.
Forecast: MEMS will capture 30% of the standard oscillator market (<±50ppm) by 2028, but crystal oscillators will remain dominant in total market value due to higher ASP of precision segments.
## Supply Chain Dynamics
Japan (NDK, KDS, Epson) historically held 55% of global crystal supply. The 2021–2023 semiconductor shortage exposed concentration risk. New capacity in China and Taiwan is reducing Japanese market share.
Chinese manufacturers (TongJing, TXC China, HubeiXDXC) are rapidly moving up the value chain from 3225 consumer-grade to automotive-grade and precision TCXO segments.
Quartz substrate: High-purity synthetic quartz remains a bottleneck. Major producers in Japan (Telling) and Russia control 70% of supply. New synthetic quartz capacity under construction in China will ease this constraint by 2027.
## Regional Outlook
China: Fastest growth at 12% CAGR, driven by domestic 5G and EV manufacturing. Government subsidies for semiconductor supply chain independence accelerating investment.
Southeast Asia: Emerging manufacturing hub for consumer electronics. Vietnam and Thailand becoming significant crystal resonator assembly locations.
USA: Defense and aerospace driving precision oscillator demand. Export controls on advanced TCXO/OCXO components creating supply constraints for Chinese manufacturers.
`,
  },
  {
    slug: 'japan-earthquake-disrupts-crystal-supply-chain',
    title: "Japan Earthquake Disrupts Global Crystal Component Supply Chain",
    category: 'industry' as const,
    date: '2026-04-02',
    author: "China NewChip",
    excerpt: "A magnitude 7.1 earthquake off the coast of Kyushu has disrupted operations at three major Japanese crystal component factories, potentially tightening global supply for automotive and industrial crystals through Q3 2026.",
    content: `
## Affected Facilities
NDK (Nihon Dempa Kogyo): Factory in Miyazaki Prefecture (produces automotive crystals) has suspended operations for safety inspection. Estimated restart: 3–4 weeks.
KDS (Kyocera Device): Factory in Nagano Prefecture (precision TCXO) reported structural damage to one production building. Full production restart: 6–8 weeks.
Epson: Factory in Akita Prefecture (consumer and industrial crystals) experienced power outage and equipment damage. Limited production resumed after 10 days.
## Supply Impact by Segment
Automotive crystals (AEC-Q100/Q200): High risk of shortage through Q3. NDK Miyazaki supplies 30% of Japanese automotive crystal market. Tier-1 EMS providers have been notified of 4–8 week delays.
Precision TCXO for telecom: KDS Nagano is a major TCXO supplier to Ericsson and Nokia. Inventory at distributors covers approximately 3 weeks of demand.
Consumer crystals (3225, 2520): Moderate impact. Alternative capacity in Taiwan and China available. Price increases of 5–10% expected at distributors through April.
## Price Movements
Distributor stock for automotive-grade crystals increased 15–25% in the week following the earthquake on anticipation of shortages.
Factory direct pricing for Q2 remains unchanged under existing contracts, but spot market premiums of 20–30% reported for automotive grades.
Long-term contracts (>1 year) typically locked at fixed pricing, protecting large buyers. Small and medium OEMs are most exposed to spot market volatility.
## Mitigation Strategies for Buyers
Alternative sourcing: Qualification of secondary suppliers takes 3–6 months for automotive, 2–4 weeks for consumer. Start qualification now to have alternatives ready by Q3.
Buffer stock: Distributors recommend 8–12 weeks of buffer inventory for automotive grades given continued uncertainty.
MEMS substitution: For non-safety-critical applications, MEMS oscillators from SiTime or Microchip can substitute for standard crystal oscillators (25MHz to 50MHz) with minimal hardware changes.
Long-term contracts: Lock in 12-month pricing and allocation with major suppliers now to avoid Q3 spot market exposure.
`,
  },
  {
    slug: 'rise-of-chinese-crystal-manufacturers',
    title: "The Rise of Chinese Crystal Manufacturers: From Low-Cost Copy to Tier-1 Quality",
    category: 'industry' as const,
    date: '2026-03-25',
    author: "China NewChip",
    excerpt: "Chinese crystal resonator manufacturers have undergone a dramatic transformation over the past decade. Once dismissed as low-quality knockoffs, several Chinese brands now meet or exceed Japanese competitors in precision, reliability, and automotive certification.",
    content: `
## Historical Context
2010–2015: Chinese crystal manufacturers primarily served the low-end consumer market. Products were often copies of Japanese designs with lower material quality and less rigorous testing. Primary value proposition: 30–40% lower price.
2015–2020: As Chinese smartphone manufacturing grew, local suppliers gained scale. Brands like TongJing, TXC China, and HubeiXDXC invested heavily in automated production lines and in-house testing equipment.
2020–present: Automotive electrification in China created demand for AEC-Q100/200 qualified crystals. Chinese EV manufacturers (BYD, NIO, Xpeng) prefer domestic suppliers for supply chain control and faster response times.
## Quality Improvements
Crystal blank manufacturing: Chinese manufacturers now produce synthetic quartz crystal blanks in-house with purity levels matching Japanese standards (99.9999% SiO₂). Some have adopted MCZ (Magnetic Czochralski) growth for larger, lower-defect blanks.
Precision tolerance: Many Chinese manufacturers now achieve ±5ppm and ±10ppm tolerances at volume, matching NDK and KDS. Tight-tolerance crystals (AEC-Q200) are no longer exclusively a Japanese domain.
Testing and certification: Major Chinese manufacturers have invested in in-house frequency tolerance testing, thermal cycling, and vibration testing. Third-party AEC-Q certification (by SGS, TÜV) is now standard for automotive grades.
## Competitive Advantages of Chinese Manufacturers Today
Shorter lead times: 2–4 weeks vs. 8–12 weeks from Japan. Faster response to design changes and volume ramp.
Lower logistics cost: No import tariffs, duties, or currency fluctuation risk for Chinese domestic buyers.
Technical support: Direct engineering support from the manufacturer rather than through a distributor. Faster resolution of application issues.
Customization: Willingness to produce non-standard frequencies, tolerances, and packages for high-volume customers.
## Remaining Gaps
Ultra-precision OCXO (>±0.001ppm): Still dominated by US and European specialty manufacturers (Microchip, Bliley, rakon). Chinese manufacturers have not yet entered this segment.
Phase noise performance: At frequencies above 100MHz, Japanese and US oscillators still lead in ultra-low-phase-noise specifications for radar and test equipment.
Brand recognition: In Western markets, Japanese brands retain strong preference, particularly in aerospace and defense. Chinese brands are gaining in Southeast Asia, India, and Africa.
`,
  },
  {
    slug: 'tongjing-launches-automotive-crystal-production-line',
    title: "TongJing Electronics Launches New Automotive Crystal Production Line with IATF 16949 Certification",
    category: 'company' as const,
    date: '2026-04-20',
    author: "China NewChip",
    excerpt: "TongJing Electronics announces the commissioning of its dedicated automotive crystal production line at its Shenzhen facility, achieving IATF 16949:2016 certification and tripling automotive-grade crystal capacity.",
    content: `
## New Production Line Details
Investment: RMB 120 million (~$16.5 million USD). Production area: 3,000 square meters. Equipment: Fully automated Japanese and German-made crystal processing and testing equipment.
Capacity: 50 million automotive-grade crystal units per month at full ramp (target: Q4 2026). Current production: 15 million/month. Expansion in two phases.
Product range: SMD2016, SMD2520, SMD3225, and SMD5032 packages. Frequency range: 4MHz to 54MHz. AEC-Q200 Grade 1 certified (-40°C to +125°C) for all automotive products.
## IATF 16949 Certification
IATF 16949:2016 is the global quality management standard for the automotive supply chain. Certification was achieved after a 6-month audit by TÜV Rheinland.
The audit covered: Process control, incoming material inspection, in-process testing, finished goods testing, traceability system, customer-specific requirements, and continuous improvement processes.
TongJing is now listed in the IATF database, allowing direct supply to Tier-1 automotive electronics suppliers globally.
## Production Control and Traceability
Each crystal lot is traceable to: Raw quartz batch, crystal blank production date, lapping and etching records, electrode deposition parameters, and final test data (frequency, ESR, CL, temperature curve).
Automated visual inspection of every unit before packaging. 100% testing of frequency tolerance, ESR, and load capacitance vs. 2% sampling at most competitors.
Statistical Process Control (SPC) running on all critical parameters. Cpk values >1.67 on all major characteristics, exceeding the automotive minimum of 1.33.
## Market Opportunity
China EV market: 12 million units sold in 2025, projected 18 million in 2026. Each EV uses 80–120 crystals, creating significant demand for domestically produced automotive-grade components.
Target customers: Major Chinese EV OEMs (BYD, NIO, Xpeng, Li Auto) and their Tier-1 EMS partners. Export to European and Southeast Asian automotive electronics manufacturers.
Pricing: 15–20% below comparable Japanese AEC-Q200 products, with equivalent or better quality as demonstrated by third-party testing data.
`,
  },
  {
    slug: 'tongjing-partnership-with-arrow-electronics',
    title: "TongJing Electronics Establishes Strategic Partnership with Arrow Electronics",
    category: 'company' as const,
    date: '2026-04-12',
    author: "China NewChip",
    excerpt: "TongJing Electronics and Arrow Electronics announce a global distribution partnership, giving Arrow customers access to TongJing automotive-grade crystal resonators and oscillators through Arrow's worldwide sales network.",
    content: `
## Partnership Scope
Arrow Electronics becomes the authorized global distributor for TongJing Electronics crystal products outside of Greater China.
Product line: Full range of TongJing crystal resonators (SMD1610 to SMD3225), crystal oscillators (SPXO, TCXO, VCXO), and RTC modules.
Initial focus: Automotive-grade products (AEC-Q100/Q200). Expansion to industrial and consumer grades planned for Q3 2026.
Arrow will hold strategic inventory of top 50 TongJing part numbers at distribution centers in US, Germany, Singapore, and Mexico.
## Technical Support
Arrow's FAE (Field Application Engineer) team has completed TongJing product training. Application support available for crystal selection, circuit design review, and troubleshooting.
TongJing will provide Arrow with reference designs for popular MCU platforms (STM32, ESP32, nRF52, Renesas RA), reducing design-in time for customers.
Joint marketing: Technical webinars, datasheet localization, and presence at major trade shows (electronica, embedded world, APEC).
## What This Means for Customers
Faster sourcing: Arrow's same-day shipping on in-stock items, 24/7 online ordering, and same-lot traceability for automotive customers.
Design-in support: Free samples for qualified automotive projects. Sample quantity: 100–500 units depending on application.
Supply chain resilience: Dual-source option for customers previously dependent on single-source Japanese suppliers. Arrow's global logistics network reduces lead times by 60–70% compared to factory-direct.
## Joint Development Roadmap
2026 Q3: Co-developed reference design for automotive cluster MCUs using TongJing TCXO + NXP S32K3 platform.
2026 Q4: Automotive camera module reference design with TongJing crystal + Sony IMX sensor + Renesas R-Car.
2027: Next-generation precision RTC module targeting V2X and telematics applications.
`,
  },
  {
    slug: 'inside-tongjing-electronics-manufacturing-process',
    title: "Inside TongJing Electronics: From Raw Quartz to Finished Crystal",
    category: 'company' as const,
    date: '2026-03-30',
    author: "China NewChip",
    excerpt: "A behind-the-scenes look at the crystal resonator manufacturing process at TongJing Electronics — from synthetic quartz crystal growth to final test and packaging.",
    content: `
## Stage 1: Synthetic Quartz Crystal Growth
TongJing sources high-purity synthetic quartz bars from certified suppliers (purity: 99.9999% SiO₂). The quartz is tested for R-point defects, bubble content, and Q-factor before acceptance.
Quartz bars are precision-sliced into wafers using inner-diameter diamond saws. Slice thickness is calculated based on target frequency — for a 26MHz crystal, wafer thickness is approximately 65μm.
Surface roughness after slicing: <0.5μm. Wafers are inspected under 100x magnification for cracks, chips, and inclusions.
## Stage 2: Crystal Blank Processing
Individual crystal blanks are cut from wafers using ultrasonic cutting. Blanks are shaped to exact dimensions using lapping and polishing processes.
The blanks are then chemically etched to remove surface damage from cutting. Etchant: hydrofluoric acid-based solution. Etch depth: 5–10μm per side.
AT-cut angle verification: Crystal blanks are oriented to the AT-cut crystal orientation (±2 arc-minutes tolerance). Misorientation causes temperature drift characteristics to deviate from specifications.
Final blank inspection: Surface roughness <0.1μm, dimension tolerance ±5μm, visual inspection at 50x magnification.
## Stage 3: Electrode Deposition
Gold or silver electrodes are deposited on both sides of the crystal blank using vacuum evaporation or sputtering. Electrode pattern defines the resonant frequency through mass-loading effects.
Electrode thickness is precisely controlled (±0.01μm). A 0.05μm difference in electrode thickness can shift frequency by 50–100ppm at 26MHz.
Hanging wires (for leaded crystals) or pad contacts (for SMD) are attached using thermosonic bonding. Bond strength: >5g pull force.
## Stage 4: Crystal Mounting and Sealing
SMD crystals: The crystal blank is mounted on a ceramic base using conductive adhesive or solder. Lid sealing is done in a controlled atmosphere (nitrogen or vacuum) to prevent moisture ingress.
Leaded crystals: The blank is mounted on lead frames using spring clips or conductive adhesive. The case is sealed using resistance welding or glass-to-metal sealing.
Seal integrity test: Helium leak testing (sensitivity: 1×10⁻⁸ atm·cc/s). Every unit tested for hermeticity.
## Stage 5: Final Testing and Quality Control
Frequency test: Each crystal is tested at 25°C for frequency (within ±10ppm tolerance), ESR (within specification), and load capacitance.
Temperature cycling: Samples from each lot are tested from -40°C to +125°C to verify temperature stability. Full temperature curve measurement for AEC-Q100 Grade 1.
Accelerated life testing (ALT): Samples subjected to 85°C/85% RH (humidity), 1000 hours. Final frequency shift must be within ±5ppm after ALT.
100% automated testing on every unit: Frequency, ESR, CL, insulation resistance. No manual sampling — every unit meets datasheet specifications before shipment.
## Traceability System
Every reel of crystals is labeled with a lot code traceable to: Quartz batch, crystal blank production date, shift (day/night), operator ID, and test data.
TongJing maintains lot records for 15 years per automotive customer requirements. Quality data available on request within 48 hours.
`,
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}

export function getAllArticles(): Article[] {
  return articles;
}

export function getArticlesByCategory(category: Article['category']): Article[] {
  return articles.filter((a) => a.category === category);
}
