// Brand data loaded from brands.json (generated by prebuild)
import brandsData from './brands.json';

export interface Brand {
  id: string;
  slug: string;
  name: Record<string, string>;
  tagline: Record<string, string>;
  description: Record<string, string>;
  logo?: string;
  primaryColor: string;
  website?: string;
  categories?: string[];
  featured?: boolean;
}

// Transform raw brand data to Brand interface
function transformBrand(raw: any): Brand {
  return {
    id: raw.id || raw.slug,
    slug: raw.slug,
    name: raw.name_localized || { en: raw.name || raw.slug, zh: raw.name || raw.slug },
    tagline: { en: raw.tagline || '' },
    description: raw.description_localized || { en: raw.description || '' },
    logo: raw.logo_url || '',
    primaryColor: raw.primaryColor || '#2563EB',
    website: raw.website || '',
    categories: raw.categories || [],
    featured: raw.featured || false,
  };
}

// Load brands from JSON
const rawBrands: any[] = Array.isArray(brandsData) ? brandsData : [];
export const brands: Brand[] = rawBrands.map(transformBrand);

export function getBrand(idOrSlug: string): Brand | undefined {
  return brands.find(b => b.id === idOrSlug || b.slug === idOrSlug);
}

export function getBrandBySlug(slug: string): Brand | undefined {
  return brands.find(b => b.slug === slug);
}

export function getAllBrands(): Brand[] {
  return brands;
}
