// Generated by scripts/feishu/sync.ts — do not edit manually
// Sync: npx tsx scripts/feishu/sync.ts brands

export interface Brand {
  id: string;
  slug: string;
  name: Record<string, string>;
  tagline: Record<string, string>;
  description: Record<string, string>;
  logo?: string;
  primaryColor: string;
  website?: string;
}

export const brands: Brand[] = [
  {
    id: 'tongjing-tj3225k',
    slug: 'tongjing',
    name: { en: 'TJ3225K-26.000M' },
    tagline: { en: 'resonator' },
    description: { en: '26MHz' },
    primaryColor: '±10ppm',
    website: 'SMD3225',
  },
  {
    id: 'tongjing-tj2520k',
    slug: 'tongjing',
    name: { en: 'TJ2520K-24.000M' },
    tagline: { en: 'resonator' },
    description: { en: '24MHz' },
    primaryColor: '±20ppm',
    website: 'SMD2520',
  },
  {
    id: 'tongjing-tj2016k',
    slug: 'tongjing',
    name: { en: 'TJ2016K-16.000M' },
    tagline: { en: 'resonator' },
    description: { en: '16MHz' },
    primaryColor: '±10ppm',
    website: 'SMD2016',
  },
  {
    id: 'tongjing-tj3225o',
    slug: 'tongjing',
    name: { en: 'TJ3225O-25.000M' },
    tagline: { en: 'oscillator' },
    description: { en: '25MHz' },
    primaryColor: '±50ppm',
    website: 'SMD3225',
  },
  {
    id: 'tongjing-tj1610k',
    slug: 'tongjing',
    name: { en: 'TJ1610K-12.000M' },
    tagline: { en: 'resonator' },
    description: { en: '12MHz' },
    primaryColor: '±20ppm',
    website: 'SMD1610',
  },
  {
    id: 'tongjing-tj2520o',
    slug: 'tongjing',
    name: { en: 'TJ2520O-40.000M' },
    tagline: { en: 'oscillator' },
    description: { en: '40MHz' },
    primaryColor: '±30ppm',
    website: 'SMD2520',
  },
];

export function getBrand(idOrSlug: string): Brand | undefined {
  return brands.find(b => b.id === idOrSlug || b.slug === idOrSlug);
}

export function getBrandBySlug(slug: string): Brand | undefined {
  return brands.find(b => b.slug === slug);
}

export function getAllBrands(): Brand[] {
  return brands;
}