// Generated by scripts/feishu/sync.ts — do not edit manually
// Sync: npx tsx scripts/feishu/sync.ts crossref

export interface CrossRefItem {
  tongjing: string;
  epson?: string;
  ndk?: string;
  kds?: string;
  murata?: string;
  package: '3225' | '2520' | '2016' | '1610';
  productId: string;
}

export interface CrossRefProduct extends CrossRefItem {
  href: string;
}

export const crossRefData: CrossRefItem[] = [
  { tongjing: 'tongjing-tj3225k', epson: 'tongjing', ndk: 'TJ3225K-26.000M', kds: 'resonator', murata: '26MHz', package: '±10ppm' as const, productId: 'SMD3225' },
  { tongjing: 'tongjing-tj2520k', epson: 'tongjing', ndk: 'TJ2520K-24.000M', kds: 'resonator', murata: '24MHz', package: '±20ppm' as const, productId: 'SMD2520' },
  { tongjing: 'tongjing-tj2016k', epson: 'tongjing', ndk: 'TJ2016K-16.000M', kds: 'resonator', murata: '16MHz', package: '±10ppm' as const, productId: 'SMD2016' },
  { tongjing: 'tongjing-tj3225o', epson: 'tongjing', ndk: 'TJ3225O-25.000M', kds: 'oscillator', murata: '25MHz', package: '±50ppm' as const, productId: 'SMD3225' },
  { tongjing: 'tongjing-tj1610k', epson: 'tongjing', ndk: 'TJ1610K-12.000M', kds: 'resonator', murata: '12MHz', package: '±20ppm' as const, productId: 'SMD1610' },
  { tongjing: 'tongjing-tj2520o', epson: 'tongjing', ndk: 'TJ2520O-40.000M', kds: 'oscillator', murata: '40MHz', package: '±30ppm' as const, productId: 'SMD2520' },
];

export function getCrossRefWithHref(): CrossRefProduct[] {
  return crossRefData.map(item => ({
    ...item,
    href: `/products/${item.productId}`,
  }));
}

export function searchCrossRef(query: string, brand?: string): CrossRefProduct[] {
  if (!query && !brand) return getCrossRefWithHref();
  if (!query) return getCrossRefWithHref().filter(item => {
    const brandKey = brand as keyof CrossRefItem;
    return item[brandKey] !== undefined;
  });

  const q = query.toLowerCase().trim();
  return getCrossRefWithHref().filter(item => {
    if (brand && brand !== 'all') {
      const brandKey = brand as keyof CrossRefItem;
      const brandValue = item[brandKey];
      if (brandValue && !brandValue.toLowerCase().includes(q)) return false;
    } else {
      const searchStr = `${item.tongjing} ${item.epson || ''} ${item.ndk || ''} ${item.kds || ''} ${item.murata || ''}`.toLowerCase();
      if (!searchStr.includes(q)) return false;
    }
    return true;
  });
}