// Generated by scripts/feishu/sync.ts — do not edit manually
// Sync: npx tsx scripts/feishu/sync.ts products

export interface Product {
  id: string;
  brandId: string;
  model: string;
  category: 'resonator' | 'oscillator' | 'rtc';
  frequency: string;
  tolerance: string;
  package: string;
  loadCapacitance: string;
  esr: string;
  stock: string;
  priceRange: string;
  badge: 'hot' | 'new' | 'default' | 'discontinued' | 'futures';
  specifications: Record<string, string>;
}

export const products: Product[] = [
  {
    id: 'tongjing-tj3225k',
    brandId: 'tongjing',
    model: 'TJ3225K-26.000M',
    category: 'resonator',
    frequency: '26MHz',
    tolerance: '±10ppm',
    package: 'SMD3225',
    loadCapacitance: '12pF',
    esr: '30Ω',
    stock: '500,000 PCS',
    priceRange: '$0.08 - $0.12',
    badge: 'hot',
    specifications: {
      'Package': '3.2×2.5×0.8mm',
      'Load Capacitance': '12pF',
      'ESR': '30Ω max',
      'Operating Temp': '-40°C to +85°C'
    },
  },
  {
    id: 'tongjing-tj2520k',
    brandId: 'tongjing',
    model: 'TJ2520K-24.000M',
    category: 'resonator',
    frequency: '24MHz',
    tolerance: '±20ppm',
    package: 'SMD2520',
    loadCapacitance: '12pF',
    esr: '40Ω',
    stock: '320,000 PCS',
    priceRange: '$0.07 - $0.10',
    badge: 'new',
    specifications: {
      'Package': '2.5×2.0×0.65mm',
      'Load Capacitance': '12pF',
      'ESR': '40Ω max',
      'Operating Temp': '-40°C to +85°C'
    },
  },
  {
    id: 'tongjing-tj2016k',
    brandId: 'tongjing',
    model: 'TJ2016K-16.000M',
    category: 'resonator',
    frequency: '16MHz',
    tolerance: '±10ppm',
    package: 'SMD2016',
    loadCapacitance: '8pF',
    esr: '50Ω',
    stock: '180,000 PCS',
    priceRange: '$0.06 - $0.09',
    badge: 'default',
    specifications: {
      'Package': '2.0×1.6×0.5mm',
      'Load Capacitance': '8pF',
      'ESR': '50Ω max',
      'Operating Temp': '-40°C to +85°C'
    },
  },
  {
    id: 'tongjing-tj3225o',
    brandId: 'tongjing',
    model: 'TJ3225O-25.000M',
    category: 'oscillator',
    frequency: '25MHz',
    tolerance: '±50ppm',
    package: 'SMD3225',
    loadCapacitance: '20pF',
    esr: '30Ω',
    stock: '2 weeks lead time',
    priceRange: '$0.10 - $0.15',
    badge: 'futures',
    specifications: {
      'Package': '3.2×2.5×1.0mm',
      'Load Capacitance': '20pF',
      'ESR': '30Ω max',
      'Operating Temp': '-40°C to +85°C'
    },
  },
  {
    id: 'tongjing-tj1610k',
    brandId: 'tongjing',
    model: 'TJ1610K-12.000M',
    category: 'resonator',
    frequency: '12MHz',
    tolerance: '±20ppm',
    package: 'SMD1610',
    loadCapacitance: '8pF',
    esr: '60Ω',
    stock: '85,000 PCS',
    priceRange: '$0.05 - $0.07',
    badge: 'default',
    specifications: {
      'Package': '1.6×1.0×0.35mm',
      'Load Capacitance': '8pF',
      'ESR': '60Ω max',
      'Operating Temp': '-40°C to +85°C'
    },
  },
  {
    id: 'tongjing-tj2520o',
    brandId: 'tongjing',
    model: 'TJ2520O-40.000M',
    category: 'oscillator',
    frequency: '40MHz',
    tolerance: '±30ppm',
    package: 'SMD2520',
    loadCapacitance: '15pF',
    esr: '40Ω',
    stock: '150,000 PCS',
    priceRange: '$0.09 - $0.13',
    badge: 'default',
    specifications: {
      'Package': '2.5×2.0×0.9mm',
      'Load Capacitance': '15pF',
      'ESR': '40Ω max',
      'Operating Temp': '-40°C to +85°C'
    },
  },
  // Test products below
  {
    id: 'tongjing-tj3225k-aec',
    brandId: 'tongjing',
    model: 'TJ3225K-26.000M-AEC',
    category: 'resonator',
    frequency: '26MHz',
    tolerance: '±10ppm',
    package: 'SMD3225',
    loadCapacitance: '12pF',
    esr: '30Ω',
    stock: '200,000 PCS',
    priceRange: '$0.15 - $0.22',
    badge: 'new',
    specifications: {
      'Package': '3.2×2.5×0.8mm',
      'Load Capacitance': '12pF',
      'ESR': '30Ω max',
      'Operating Temp': '-40°C to +125°C',
      'AEC-Q200': 'Grade 1',
      'Frequency Tolerance': '±10ppm at 25°C',
      'Shelf Life': '2 years at 25°C'
    },
  },
  {
    id: 'tongjing-tj2520k-aec',
    brandId: 'tongjing',
    model: 'TJ2520K-16.000M-AEC',
    category: 'resonator',
    frequency: '16MHz',
    tolerance: '±10ppm',
    package: 'SMD2520',
    loadCapacitance: '8pF',
    esr: '40Ω',
    stock: '120,000 PCS',
    priceRange: '$0.12 - $0.18',
    badge: 'new',
    specifications: {
      'Package': '2.5×2.0×0.65mm',
      'Load Capacitance': '8pF',
      'ESR': '40Ω max',
      'Operating Temp': '-40°C to +125°C',
      'AEC-Q200': 'Grade 1',
      'Frequency Tolerance': '±10ppm at 25°C'
    },
  },
  {
    id: 'tongjing-tj2016k-38.4m',
    brandId: 'tongjing',
    model: 'TJ2016K-38.400M',
    category: 'resonator',
    frequency: '38.4MHz',
    tolerance: '±10ppm',
    package: 'SMD2016',
    loadCapacitance: '8pF',
    esr: '50Ω',
    stock: '75,000 PCS',
    priceRange: '$0.07 - $0.11',
    badge: 'default',
    specifications: {
      'Package': '2.0×1.6×0.5mm',
      'Load Capacitance': '8pF',
      'ESR': '50Ω max',
      'Operating Temp': '-40°C to +85°C',
      'Frequency Tolerance': '±10ppm at 25°C',
      'Application': 'ESP32 WiFi/BLE'
    },
  },
  {
    id: 'tongjing-tj3225o-32m-aec',
    brandId: 'tongjing',
    model: 'TJ3225O-32.000M-AEC',
    category: 'oscillator',
    frequency: '32MHz',
    tolerance: '±20ppm',
    package: 'SMD3225',
    loadCapacitance: '12pF',
    esr: '30Ω',
    stock: '180,000 PCS',
    priceRange: '$0.18 - $0.25',
    badge: 'hot',
    specifications: {
      'Package': '3.2×2.5×1.0mm',
      'Load Capacitance': '12pF',
      'ESR': '30Ω max',
      'Operating Temp': '-40°C to +125°C',
      'AEC-Q100': 'Grade 1',
      'Startup Time': '5ms max',
      'Application': 'nRF52 BLE, STM32 USB'
    },
  },
  {
    id: 'tongjing-tj1610k-24m',
    brandId: 'tongjing',
    model: 'TJ1610K-24.000M',
    category: 'resonator',
    frequency: '24MHz',
    tolerance: '±20ppm',
    package: 'SMD1610',
    loadCapacitance: '8pF',
    esr: '60Ω',
    stock: '60,000 PCS',
    priceRange: '$0.05 - $0.08',
    badge: 'default',
    specifications: {
      'Package': '1.6×1.0×0.35mm',
      'Load Capacitance': '8pF',
      'ESR': '60Ω max',
      'Operating Temp': '-40°C to +85°C',
      'Frequency Tolerance': '±20ppm at 25°C',
      'Application': 'Wearables, IoT sensors'
    },
  },
  {
    id: 'tongjing-tj2520o-8m-aec',
    brandId: 'tongjing',
    model: 'TJ2520O-8.000M-AEC',
    category: 'oscillator',
    frequency: '8MHz',
    tolerance: '±30ppm',
    package: 'SMD2520',
    loadCapacitance: '12pF',
    esr: '50Ω',
    stock: '90,000 PCS',
    priceRange: '$0.11 - $0.16',
    badge: 'default',
    specifications: {
      'Package': '2.5×2.0×0.9mm',
      'Load Capacitance': '12pF',
      'ESR': '50Ω max',
      'Operating Temp': '-40°C to +125°C',
      'AEC-Q200': 'Grade 1',
      'Frequency Tolerance': '±30ppm at 25°C',
      'Application': 'Automotive CAN/LIN'
    },
  },
  {
    id: 'tongjing-tj3225k-40m',
    brandId: 'tongjing',
    model: 'TJ3225K-40.000M',
    category: 'resonator',
    frequency: '40MHz',
    tolerance: '±10ppm',
    package: 'SMD3225',
    loadCapacitance: '8pF',
    esr: '30Ω',
    stock: '280,000 PCS',
    priceRange: '$0.09 - $0.13',
    badge: 'default',
    specifications: {
      'Package': '3.2×2.5×0.8mm',
      'Load Capacitance': '8pF',
      'ESR': '30Ω max',
      'Operating Temp': '-40°C to +85°C',
      'Frequency Tolerance': '±10ppm at 25°C',
      'Application': 'Ethernet PHY, USB host'
    },
  },
  {
    id: 'tongjing-tj2016k-aec',
    brandId: 'tongjing',
    model: 'TJ2016K-26.000M-AEC',
    category: 'resonator',
    frequency: '26MHz',
    tolerance: '±10ppm',
    package: 'SMD2016',
    loadCapacitance: '10pF',
    esr: '50Ω',
    stock: '95,000 PCS',
    priceRange: '$0.13 - $0.19',
    badge: 'new',
    specifications: {
      'Package': '2.0×1.6×0.5mm',
      'Load Capacitance': '10pF',
      'ESR': '50Ω max',
      'Operating Temp': '-40°C to +125°C',
      'AEC-Q200': 'Grade 1',
      'Frequency Tolerance': '±10ppm at 25°C',
      'Application': 'ADAS, cluster MCUs'
    },
  },
  {
    id: 'tongjing-tj2520o-tcxo',
    brandId: 'tongjing',
    model: 'TJ2520TCXO-19.200M',
    category: 'oscillator',
    frequency: '19.2MHz',
    tolerance: '±2.5ppm',
    package: 'SMD2520',
    loadCapacitance: 'N/A',
    esr: 'N/A',
    stock: '35,000 PCS',
    priceRange: '$0.45 - $0.65',
    badge: 'hot',
    specifications: {
      'Package': '2.5×2.0×0.9mm',
      'Output Type': 'CMOS',
      'Supply Voltage': '3.3V ±5%',
      'Frequency Stability': '±2.5ppm over -40°C to +85°C',
      'Phase Noise': '-130dBc/Hz @ 1kHz',
      'Application': 'GPS, GNSS, precision timing'
    },
  },
  {
    id: 'tongjing-tj3225o-50m',
    brandId: 'tongjing',
    model: 'TJ3225O-50.000M',
    category: 'oscillator',
    frequency: '50MHz',
    tolerance: '±30ppm',
    package: 'SMD3225',
    loadCapacitance: '15pF',
    esr: '25Ω',
    stock: '110,000 PCS',
    priceRange: '$0.12 - $0.17',
    badge: 'default',
    specifications: {
      'Package': '3.2×2.5×1.0mm',
      'Load Capacitance': '15pF',
      'ESR': '25Ω max',
      'Operating Temp': '-40°C to +85°C',
      'Frequency Tolerance': '±30ppm at 25°C',
      'Application': 'FPGA clocks, serializers'
    },
  },
];

export function getProductsByBrand(brandId: string): Product[] {
  return products.filter(p => p.brandId === brandId);
}

export function getProductBySlug(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductByModel(model: string): Product | undefined {
  return products.find(p => p.model === model);
}

export function getAllProducts(): Product[] {
  return products;
}